[app]
log = "debug"
domain = "http://localhost:7777"

[server]
address = "0.0.0.0:7777"
timeout = "7s"
idle_timeout = "30s"

[db]
host = "127.0.0.1"
port = 9000
name = "monkeybeat"
user = ""
password = ""
